#!/usr/bin/env python3
"""Turn Natural Earth's GeoJSON into world.toml, the data file the
capitals game reads with X_eTaL's []L_IST and []T_ABLE. Plain values
only: X_eTaL chooses the projection, places every dot and draws the
map. TOML lists hold strings, so numbers are written as strings.

  convert.py COUNTRIES.geojson PLACES.geojson OUT.toml

countries  one string per country (unlabeled), its outline as SVG path
           data in plain degrees: "M lon lat L lon lat ... Z M ...",
           latitude north up as written (X_eTaL's transform flips it);
           points closer than 0.2 degree to the last one kept are
           dropped, but every ring keeps at least three
places     the keys of the national capitals, sorted by name
fields     name, lat, lon, region (place.K: "Capital, Country",
           degrees, its country's UN region)
cities     the keys (c1, c2, ...) of every populated place, capitals
           too, for the wrong choices; city.K: name, lat, lon
"""
import json, sys

countries, places, out = sys.argv[1:4]
feats = json.load(open(countries))["features"]
region = {}
for f in feats:
    q = f["properties"]
    for k in ("ADM0_A3", "SOV_A3"):
        region.setdefault(q[k], q["REGION_UN"])

def ring(r):
    keep = [r[0]]
    for p in r[1:-1]:
        if abs(p[0] - keep[-1][0]) + abs(p[1] - keep[-1][1]) >= 0.2:
            keep.append(p)
    if len(keep) < 3:
        keep = r[:-1][:max(3, len(keep))]
    pts = " L ".join(f"{x:.2f} {y:.2f}".replace(".00", "") for x, y in keep)
    return f"M {pts} Z"

outlines = []
for f in feats:
    g = f["geometry"]
    polys = [g["coordinates"]] if g["type"] == "Polygon" else g["coordinates"]
    outlines.append(" ".join(ring(r) for poly in polys for r in poly))

pp = [f["properties"] for f in json.load(open(places))["features"]]
key = lambda p: (p["NAMEASCII"] + "-" + p["ADM0_A3"]).lower().replace(" ", "-").replace("'", "").replace(".", "")
caps = sorted((p for p in pp if p["ADM0CAP"] == 1), key=lambda p: p["NAMEASCII"])
q = lambda s: '"' + s.replace('"', "") + '"'
with open(out, "w") as w:
    w.write("# Generated by games/capitals/assets/convert.py from Natural Earth\n"
            "# (public domain); not tracked. See assets/fetch.sh.\n\n")
    w.write("countries = [\n" + ",\n".join(q(o) for o in outlines) + "\n]\n")
    w.write("places = [" + ", ".join(q(key(p)) for p in caps) + "]\n")
    w.write('fields = ["name", "lat", "lon", "region"]\n')
    w.write("cities = [" + ", ".join(f'"c{i}"' for i in range(1, len(pp) + 1)) + "]\n")
    w.write('cityfields = ["name", "lat", "lon"]\n')
    for p in caps:
        r = region.get(p["ADM0_A3"]) or region.get(p["SOV_A3"]) or ""
        w.write(f'\n[place.{q(key(p))}]\nname = {q(p["NAMEASCII"] + ", " + p["ADM0NAME"])}\n'
                f'lat = "{p["LATITUDE"]:.2f}"\nlon = "{p["LONGITUDE"]:.2f}"\nregion = "{r}"\n')
    for i, p in enumerate(pp, 1):
        w.write(f'\n[city.c{i}]\nname = {q(p["NAMEASCII"])}\n'
                f'lat = "{p["LATITUDE"]:.2f}"\nlon = "{p["LONGITUDE"]:.2f}"\n')
print(f"world.toml: {len(outlines)} countries, {len(caps)} capitals, {len(pp)} cities")
