#!/usr/bin/env python3
"""Turn Natural Earth's GeoJSON into world.toml, the data file the
capitals game reads with X_eTaL's []L_IST and []T_ABLE: plain values
only, no projection (X_eTaL projects every point itself). TOML lists
hold strings, so the numbers are written as strings.

  convert.py LAND.geojson PLACES.geojson COUNTRIES.geojson OUT.toml

coast    "longitude latitude" (degrees, to 0.1) of points along every
         coastline, one at least every 0.25 degrees
places   the keys of the 199 national capitals, sorted by name
fields   the columns of each place: name, lat, lon, region
place.K  a capital: "Capital, Country", latitude and longitude
         (degrees), and its country's UN region (Africa, Americas,
         Asia, Europe or Oceania)
"""
import json, math, sys

land, places, countries, out = sys.argv[1:5]
region = {}
for f in json.load(open(countries))["features"]:
    q = f["properties"]
    for k in ("ADM0_A3", "SOV_A3"):
        region.setdefault(q[k], q["REGION_UN"])
pts = set()
for f in json.load(open(land))["features"]:
    g = f["geometry"]
    for poly in [g["coordinates"]] if g["type"] == "Polygon" else g["coordinates"]:
        for ring in poly:
            for (x0, y0), (x1, y1) in zip(ring, ring[1:]):
                n = max(1, math.ceil(max(abs(x1 - x0), abs(y1 - y0)) / 0.25))
                for i in range(n):
                    t = i / n
                    pts.add((round(10 * (x0 + t * (x1 - x0))), round(10 * (y0 + t * (y1 - y0)))))
caps = sorted((p["properties"] for p in json.load(open(places))["features"]
               if p["properties"]["ADM0CAP"] == 1), key=lambda p: p["NAMEASCII"])
keys = [p["NAMEASCII"].lower().replace(" ", "-").replace("'", "").replace(".", "") for p in caps]
assert len(set(keys)) == len(keys)
q = lambda s: '"' + s.replace('"', "") + '"'
with open(out, "w") as w:
    w.write("# Generated by games/capitals/assets/convert.py from Natural Earth\n"
            "# (public domain); not tracked. See assets/fetch.sh.\n\n")
    w.write("coast = [" + ", ".join(f'"{x / 10:g} {y / 10:g}"' for x, y in sorted(pts)) + "]\n")
    w.write("places = [" + ", ".join(q(k) for k in keys) + "]\n")
    w.write('fields = ["name", "lat", "lon", "region"]\n')
    for k, p in zip(keys, caps):
        r = region.get(p["ADM0_A3"]) or region[p["SOV_A3"]]
        w.write(f'\n[place.{q(k)}]\nname = {q(p["NAMEASCII"] + ", " + p["ADM0NAME"])}\n'
                f'lat = "{p["LATITUDE"]:.2f}"\nlon = "{p["LONGITUDE"]:.2f}"\nregion = "{r}"\n')
print(f"world.toml: {len(pts)} coast points, {len(caps)} capitals")
