number = 33
slug = "asteroids"
status = "completed"
description = "an ECS demo with ticks: spawning and despawning (bullets, rocks splitting): e..."
role = "production"
context_files = []
created_at = "2026-10-09T11:07:13"
completed_at = "2026-10-10T16:48:33"
task_type = "feature"
commits = ["224833c600d4ca06a3b3ed4c4f080a63727098f2"]
