#!/usr/bin/env python3
"""Turn the Bright Star Catalog and the IAU Catalog of Star Names into
sky.toml, the data file the stargazer game reads with X_eTaL's []L_IST
and []T_ABLE. Plain values only: X_eTaL places every star and draws the
sky. TOML lists hold strings, so numbers are written as strings.

  convert.py BSC5.gz IAU-CSN.txt OUT.toml

sky     "ra dec mag" (degrees, degrees, visual magnitude) of every
        catalog star of magnitude 5.5 or brighter: the sky behind
stars   the keys of the named stars of magnitude 5 or brighter
fields  name, ra, dec, mag, con (star.K: the IAU name, J2000 degrees,
        magnitude, constellation abbreviation)
"""
import gzip, re, sys

bsc, csn, out = sys.argv[1:4]
sky = []
for line in gzip.open(bsc, "rt", encoding="latin-1"):
    if len(line) < 107 or not line[75:77].strip() or not line[102:107].strip():
        continue
    ra = 15 * (int(line[75:77]) + int(line[77:79]) / 60 + float(line[79:83]) / 3600)
    dec = int(line[84:86]) + int(line[86:88]) / 60 + int(line[88:90]) / 3600
    dec = -dec if line[83] == "-" else dec
    mag = float(line[102:107])
    if mag <= 5.5:
        sky.append((ra, dec, mag))

text = open(csn, encoding="utf-8").read().splitlines()
head = next(l for l in text if l.startswith("#Name/ASCII"))
con_at = head.index("Con")
right = re.compile(r"(-?\d+\.\d+)\s+(\S+)\s+\S+\s+\S+\s+(\d+\.\d+)\s+(-?\d+\.\d+)\s+\d{4}-\d\d-\d\d")
stars = {}
for l in text:
    if not l.strip() or l[0] in "#$":
        continue
    m = right.search(l)
    if not m:
        continue
    name, mag = l[:18].strip(), float(m.group(1))
    if mag <= 5.0 and name not in stars:
        stars[name] = (float(m.group(3)), float(m.group(4)), mag, l[con_at:con_at + 3].strip())

key = lambda n: re.sub(r"[^a-z0-9]+", "-", n.lower()).strip("-")
with open(out, "w") as w:
    w.write("# Generated by games/stargazer/assets/convert.py from the Yale Bright\n"
            "# Star Catalog (NASA, public domain) and the IAU Catalog of Star Names\n"
            "# (IAU, CC BY); not tracked. See assets/fetch.sh.\n\n")
    w.write("sky = [" + ", ".join(f'"{ra:.2f} {dec:.2f} {mag:.2f}"' for ra, dec, mag in sky) + "]\n")
    w.write("stars = [" + ", ".join(f'"{key(n)}"' for n in sorted(stars)) + "]\n")
    w.write('fields = ["name", "ra", "dec", "mag", "con"]\n')
    for n in sorted(stars):
        ra, dec, mag, con = stars[n]
        w.write(f'\n[star.{key(n)}]\nname = "{n}"\nra = "{ra:.3f}"\ndec = "{dec:.3f}"\nmag = "{mag:.2f}"\ncon = "{con}"\n')
print(f"sky.toml: {len(sky)} catalog stars, {len(stars)} named stars")
